### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [giginfee/my_parser#1]
Student: Бернацька Ольга

Не вистачає для прохідного:
✔️ ! CLI:
✔️ ! Brief Description: просто невелика нотатка. Можна не додавати  посилання на репозиторій у опис. Для цього є [окреме поле](https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field) 
✔️ ! Project Name: 
✔️ ! Grammar Rules: я зараховую
✔️ ! Unit Tests:
✔️ ! Core Files:

Не вистачає для мааксимального:
❌ File System: не бачу ні зчитування з файлу ні запис
✔️ Test Coverage: проте краще розділи тест на менші
❌ Error Handling: у lib.rs порібно використовувати thisserror, а anyhow лише у тестах
❌ cargo fmt:
❌ cargo clippy:
❌ makefile:
❌ Completeness:
❌ Including a diagram or grammar in the Readme.md: бачу лише приклад парсу, а не правила.
❌ Documentation:
❌ Publishing: після виконання виправлень оновиш

✔️ Курсова може бути зарахована
Бал: 9/25

**Comment by NYBACHOK** [comment]
Привіт. Напиши чи погоджуєшся з балом

**Comment by giginfee** [comment]
Вітаю, так погоджуюсь

пн, 20 лист. 2023 р. о 17:32 NYBACHOK ***@***.***> пише:
